name: Unit test suite

on:
  push

jobs:
  # Job for Debian Linux
  # ====================

  debian:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            packages:
            cc: gcc
            cxx: g++

          - os: ubuntu-24.04
            packages: clang
            cc: clang
            cxx: clang++

          - os: ubuntu-24.04
            packages: intel-oneapi-compiler-dpcpp-cpp
            cc: icx
            cxx: icpx

    name: |
      ${{ matrix.os }} ${{ matrix.cc }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out project
        uses: actions/checkout@v5

      - uses: gerlero/add-apt-repository@v1
        if: startsWith(matrix.packages, 'intel')
        with:
          uri: https://apt.repos.intel.com/oneapi
          key: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          suite: all

      - name: Install APT dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libmpfr-dev libeigen3-dev catch2 ${{ matrix.packages }}

      - name: CMake configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          options: |
            XPREC_BUILD_TESTING=ON
            CMAKE_C_COMPILER='${{ matrix.cc }}'
            CMAKE_CXX_COMPILER='${{ matrix.cxx }}'
          run-build: true

      - name: Run tests
        run: |
          build/test/tests

  # Job for MacOS
  # =============

  macos:
    strategy:
      matrix:
        include:
          - os: macos-latest

    name: |
      ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out project
        uses: actions/checkout@v5

      - name: Install dependencies with brew
        run: |
          brew install mpfr catch2 eigen

      - name: CMake configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          options: |
            XPREC_BUILD_TESTING=ON
          run-build: true

      - name: Run tests
        run: |
          build/test/tests

  # Job for Windows
  # ===============

  windows:
    strategy:
      matrix:
        include:
          - os: windows-latest

    name: |
      ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out project
        uses: actions/checkout@v5

      - name: CMake configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          options: |
            XPREC_BUILD_TESTING=OFF
          run-build: true
